<a href="https://colab.research.google.com/github/rubusarbaro/supplychain-forecast-FIME/blob/main/PIA_Prophet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from google.colab import userdata
import json
import pandas as pd
import requests

In [31]:
HTTP_codes = {
    "200" : "OK",
    "400" : "Bad Request",
    "401" : "Unauthorized",
    "403" : "Forbidden",
    "404" : "Not Found",
    "500" : "Internal Server Error",
}

In [33]:
serie_ID = "SF43718"
SIE_API = f"https://www.banxico.org.mx/SieAPIRest/service/v1/series/{serie_ID}/datos?token={userdata.get('Banxico_Token')}"
response = requests.get(SIE_API)

HTTP_codes[str(response.status_code)]

'OK'

In [34]:
data = response.json()
series_data = data["bmx"]["series"][0]["datos"]
df = pd.DataFrame(series_data)
df

           fecha     dato
0     12/11/1991   3.0735
1     13/11/1991   3.0712
2     14/11/1991   3.0718
3     15/11/1991   3.0684
4     18/11/1991   3.0673
...          ...      ...
8377  12/03/2025  20.1828
8378  13/03/2025  20.0848
8379  14/03/2025  19.8693
8380  18/03/2025  19.9845
8381  19/03/2025  20.0553

[8382 rows x 2 columns]

           fecha     dato
0     12/11/1991   3.0735
1     13/11/1991   3.0712
2     14/11/1991   3.0718
3     15/11/1991   3.0684
4     18/11/1991   3.0673
...          ...      ...
8377  12/03/2025  20.1828
8378  13/03/2025  20.0848
8379  14/03/2025  19.8693
8380  18/03/2025  19.9845
8381  19/03/2025  20.0553

[8382 rows x 2 columns]